import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import { TRPCReactProvider } from "~/trpc/react";
import { Banner, NavInfo, Navbar } from "./_components";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCReactProvider>
          <Toaster position="top-center" richColors closeButton />
          <main>
            <NavInfo />
            <Navbar />
            <Banner msg={"Get 10% off on business sign up"} />
            {children}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
